"""Pre-populated Sara sample analysis (richer creation history)."""

SARAH_WORK_ID = "demo-sarah-visual-artwork"

SARAH_WORK = {
    "id": SARAH_WORK_ID,
    "work_type": "Visual",
    "title": "Sara's Neon Archivist — Cover Artwork",
    "description": "A single-canvas illustration developed through human sketching, AI generation, human selection, rearrangement, face repainting, background replacement and final adjustments.",
    "is_demo": True,
}

SARAH_EVENTS = [
    {
        "creation_event_id": "EV-001",
        "sequence": 1,
        "description": "Sara creates an initial sketch specifying the subject, pose and broad composition.",
        "actor": "HUMAN",
        "timestamp": "2026-01-14T10:02:00Z",
        "certainty": "KNOWN",
        "source_files": ["Sara_initial_sketch.png"],
        "issues": ["HUMAN_CONTRIBUTION"],
    },
    {
        "creation_event_id": "EV-002",
        "sequence": 2,
        "description": "Sara provides her sketch and instructions to an AI image generator. The AI produces five substantially different outputs.",
        "actor": "AI",
        "timestamp": "2026-01-14T10:17:00Z",
        "certainty": "KNOWN",
        "source_files": ["AI_Output_01.png", "AI_Output_02.png", "AI_Output_03.png", "AI_Output_04.png", "AI_Output_05.png"],
        "issues": ["AI_GENERATED_MATERIAL"],
    },
    {
        "creation_event_id": "EV-003",
        "sequence": 3,
        "description": "Sara reviews the five AI outputs and selects Output #3 because it best matches her intended composition.",
        "actor": "HUMAN",
        "timestamp": "2026-01-14T10:23:00Z",
        "certainty": "KNOWN",
        "source_files": ["AI_Output_01.png", "AI_Output_02.png", "AI_Output_03.png", "AI_Output_04.png", "AI_Output_05.png", "Output_03_selected.png"],
        "issues": ["SELECTION_ARRANGEMENT", "HUMAN_CONTRIBUTION"],
    },
    {
        "creation_event_id": "EV-004",
        "sequence": 4,
        "description": "Sara changes the placement and scale of the subject and rearranges several visual elements in the selected AI output.",
        "actor": "HUMAN",
        "timestamp": "2026-01-14T10:31:00Z",
        "certainty": "KNOWN",
        "source_files": ["Output_03_selected.png", "Rearranged_v1.png"],
        "issues": ["SELECTION_ARRANGEMENT", "HUMAN_MODIFICATION", "HUMAN_CONTRIBUTION"],
    },
    {
        "creation_event_id": "EV-005",
        "sequence": 5,
        "description": "Sara manually repaints the face using the selected AI output as the base.",
        "actor": "HUMAN",
        "timestamp": "2026-01-14T10:44:00Z",
        "certainty": "KNOWN",
        "source_files": ["Output_03_selected.png", "Final_artwork.png"],
        "issues": ["HUMAN_MODIFICATION", "HUMAN_CONTRIBUTION"],
        "prompt_missing": True,
    },
    {
        "creation_event_id": "EV-006",
        "sequence": 6,
        "description": "Sara replaces part of the AI-generated background with elements derived from her original sketch.",
        "actor": "HUMAN",
        "timestamp": "2026-01-14T10:58:00Z",
        "certainty": "KNOWN",
        "source_files": ["Sara_initial_sketch.png", "Output_03_selected.png", "Final_artwork.png"],
        "issues": ["HUMAN_MODIFICATION", "HUMAN_CONTRIBUTION"],
    },
    {
        "creation_event_id": "EV-007",
        "sequence": 7,
        "description": "Sara makes final expressive colour and compositional adjustments to the artwork.",
        "actor": "HUMAN",
        "timestamp": "2026-01-14T11:12:00Z",
        "certainty": "KNOWN",
        "source_files": ["Final_artwork.png", "Rearranged_v1.png"],
        "issues": ["HUMAN_MODIFICATION", "HUMAN_CONTRIBUTION"],
    },
    {
        "creation_event_id": "EV-008",
        "sequence": 8,
        "description": "Sara exports the completed artwork.",
        "actor": "HUMAN",
        "timestamp": "2026-01-14T11:15:00Z",
        "certainty": "KNOWN",
        "source_files": ["Final_artwork.png"],
        "issues": [],
    },
]

SARAH_FILES = [
    {"file_id": "f-01", "file_name": "Sara_initial_sketch.png", "file_type": "human_draft", "stage": "initial_sketch",
     "timestamp": "2026-01-14T10:02:00Z", "description": "Sara's initial sketch — subject, pose, broad composition."},
    {"file_id": "f-02", "file_name": "AI_Output_01.png", "file_type": "ai_output", "stage": "ai_alternative",
     "timestamp": "2026-01-14T10:17:00Z", "description": "AI-generated alternative 1 of 5."},
    {"file_id": "f-03", "file_name": "AI_Output_02.png", "file_type": "ai_output", "stage": "ai_alternative",
     "timestamp": "2026-01-14T10:17:00Z", "description": "AI-generated alternative 2 of 5."},
    {"file_id": "f-04", "file_name": "AI_Output_03.png", "file_type": "ai_output", "stage": "ai_alternative",
     "timestamp": "2026-01-14T10:17:00Z", "description": "AI-generated alternative 3 of 5 — later selected as the working base."},
    {"file_id": "f-05", "file_name": "AI_Output_04.png", "file_type": "ai_output", "stage": "ai_alternative",
     "timestamp": "2026-01-14T10:17:00Z", "description": "AI-generated alternative 4 of 5."},
    {"file_id": "f-06", "file_name": "AI_Output_05.png", "file_type": "ai_output", "stage": "ai_alternative",
     "timestamp": "2026-01-14T10:17:00Z", "description": "AI-generated alternative 5 of 5."},
    {"file_id": "f-07", "file_name": "Output_03_selected.png", "file_type": "intermediate", "stage": "selected_base",
     "timestamp": "2026-01-14T10:23:00Z", "description": "The AI output Sara selected as the working base."},
    {"file_id": "f-08", "file_name": "Rearranged_v1.png", "file_type": "intermediate", "stage": "post_rearrangement",
     "timestamp": "2026-01-14T10:31:00Z", "description": "Selected output after Sara's rearrangement of visual elements."},
    {"file_id": "f-09", "file_name": "Final_artwork.png", "file_type": "final_work", "stage": "final",
     "timestamp": "2026-01-14T11:15:00Z", "description": "The final exported illustration."},
]
